version: 2.1

jobs:
#  build:
#    docker:
#      - image: cimg/base:stable
#    steps:
#      - checkout
#      - run: echo "This job is configured but will never run because it's commented out."

workflows:
#  version: 2
#  build_and_test:
#    jobs:
#      - build

# This config file is a placeholder and does not define any active jobs or workflows.
